const mongoose = require("mongoose");

const sampleListings = [
  {
    title: "Luxury Beachside Villa",
    desc: "A stunning villa with ocean view, private pool, and modern interiors.",
    image: {
      url: "https://images.unsplash.com/photo-1729720281814-5ddf34c69f8b",
      filename: "listing-1",
    },
    price: 15000,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.8278, 15.2993] },
    category: "trending",
  },
  {
    title: "Mountain View Cottage",
    desc: "Peaceful cottage surrounded by mountains and fresh air.",
    image: {
      url: "https://images.unsplash.com/photo-1566301738357-2e0cc60c4d40",
      filename: "listing-2",
    },
    price: 6000,
    location: "Manali",
    country: "India",
    geometry: { type: "Point", coordinates: [77.1892, 32.2396] },
    category: "mountains",
  },
  {
    title: "City Center Apartment",
    desc: "Modern apartment located in the heart of the city.",
    image: {
      url: "https://images.unsplash.com/photo-1733587820244-83fd93e30052",
      filename: "listing-3",
    },
    price: 8000,
    location: "Mumbai",
    country: "India",
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    category: "iconic",
  },
  {
    title: "Desert Camp Stay",
    desc: "Traditional desert camp experience with cultural programs.",
    image: {
      url: "https://images.unsplash.com/photo-1762970913723-21d3c7f5846c",
      filename: "listing-4",
    },
    price: 5000,
    location: "Jaisalmer",
    country: "India",
    geometry: { type: "Point", coordinates: [70.9083, 26.9157] },
    category: "desert",
  },
  {
    title: "Hilltop Resort",
    desc: "Resort offering breathtaking hill views and luxury stay.",
    image: {
      url: "https://images.unsplash.com/photo-1665930152500-26acb7c86076",
      filename: "listing-5",
    },
    price: 12000,
    location: "Ooty",
    country: "India",
    geometry: { type: "Point", coordinates: [76.695, 11.4102] },
    category: "mountains",
  },
  {
    title: "Lake View Homestay",
    desc: "Comfortable homestay overlooking a serene lake.",
    image: {
      url: "https://images.unsplash.com/photo-1563768562818-d16e87ffbf6a",
      filename: "listing-6",
    },
    price: 7000,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7125, 24.5854] },
    category: "rooms",
  },
  {
    title: "Forest Tree House",
    desc: "Unique tree house stay inside a lush green forest.",
    image: {
      url: "https://images.unsplash.com/photo-1633830902223-727413dfad8f",
      filename: "listing-7",
    },
    price: 9000,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.132, 11.6854] },
    category: "forest",
  },
  {
    title: "Royal Heritage Palace",
    desc: "Live like royalty in this beautifully restored palace.",
    image: {
      url: "https://images.unsplash.com/photo-1738482224201-eb499b160d72",
      filename: "listing-8",
    },
    price: 20000,
    location: "Jaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
    category: "castles",
  },
  {
    title: "Riverside Cottage",
    desc: "Cozy cottage located beside a flowing river.",
    image: {
      url: "https://images.unsplash.com/photo-1707044093117-970e52b649aa",
      filename: "listing-9",
    },
    price: 6500,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
    category: "rooms",
  },
  {
    title: "Luxury City Hotel",
    desc: "Premium hotel with world-class amenities.",
    image: {
      url: "https://images.unsplash.com/photo-1721539151779-e6dc7f9de376",
      filename: "listing-10",
    },
    price: 14000,
    location: "Delhi",
    country: "India",
    geometry: { type: "Point", coordinates: [77.209, 28.6139] },
    category: "iconic",
  },
  {
    title: "Backwater Houseboat",
    desc: "Relaxing houseboat experience in peaceful backwaters.",
    image: {
      url: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2",
      filename: "listing-11",
    },
    price: 11000,
    location: "Alleppey",
    country: "India",
    geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
    category: "boat",
  },
  {
    title: "Snow View Chalet",
    desc: "Wooden chalet with mesmerizing snow views.",
    image: {
      url: "https://images.unsplash.com/photo-1547632115-a85b28cbfb87",
      filename: "listing-12",
    },
    price: 10000,
    location: "Gulmarg",
    country: "India",
    geometry: { type: "Point", coordinates: [74.3805, 34.0484] },
    category: "arctic",
  },
  {
    title: "Eco Friendly Lodge",
    desc: "Sustainable lodge with eco-friendly living.",
    image: {
      url: "https://images.unsplash.com/photo-1582610116397-edb318620f90",
      filename: "listing-13",
    },
    price: 5500,
    location: "Coorg",
    country: "India",
    geometry: { type: "Point", coordinates: [75.8069, 12.3375] },
    category: "forest",
  },
  {
    title: "Beach Hut Stay",
    desc: "Simple beach hut with direct access to the shore.",
    image: {
      url: "https://images.unsplash.com/photo-1605230521018-61f2095a762a",
      filename: "listing-14",
    },
    price: 4000,
    location: "Varkala",
    country: "India",
    geometry: { type: "Point", coordinates: [76.7163, 8.7379] },
    category: "trending",
  },
  {
    title: "Luxury Penthouse",
    desc: "High-rise penthouse with skyline views.",
    image: {
      url: "https://images.unsplash.com/photo-1702411200201-3061d0eea802",
      filename: "listing-15",
    },
    price: 18000,
    location: "Bengaluru",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    category: "iconic",
  },
  {
    title: "Jungle Safari Lodge",
    desc: "Stay close to nature with guided jungle safaris.",
    image: {
      url: "https://images.unsplash.com/photo-1755448647983-529abcaa2c3e",
      filename: "listing-16",
    },
    price: 9500,
    location: "Ranthambore",
    country: "India",
    geometry: { type: "Point", coordinates: [76.5026, 26.0173] },
    category: "forest",
  },
  {
    title: "Spiritual Ashram Stay",
    desc: "Peaceful stay for meditation and yoga.",
    image: {
      url: "https://images.unsplash.com/photo-1726313017779-116885659165",
      filename: "listing-17",
    },
    price: 3000,
    location: "Varanasi",
    country: "India",
    geometry: { type: "Point", coordinates: [82.9739, 25.3176] },
    category: "spiritual",
  },
  {
    title: "Island Resort",
    desc: "Private island resort with crystal-clear waters.",
    image: {
      url: "https://images.unsplash.com/photo-1552873547-b88e7b2760e2",
      filename: "listing-18",
    },
    price: 25000,
    location: "Andaman",
    country: "India",
    geometry: { type: "Point", coordinates: [92.7265, 11.7401] },
    category: "trending",
  },
  {
    title: "Colonial Bungalow",
    desc: "Old-style bungalow with colonial architecture.",
    image: {
      url: "https://images.unsplash.com/photo-1632152683081-28923830268d",
      filename: "listing-19",
    },
    price: 8500,
    location: "Shimla",
    country: "India",
    geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
    category: "rooms",
  },
  {
    title: "Farm Stay Retreat",
    desc: "Experience rural life with modern comfort.",
    image: {
      url: "https://plus.unsplash.com/premium_photo-1723928437874-db8c3a31cbee",
      filename: "listing-20",
    },
    price: 4500,
    location: "Nashik",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7898, 19.9975] },
    category: "farms",
  },
  {
    title: "Luxury Desert Resort",
    desc: "Premium desert resort with cultural shows.",
    image: {
      url: "https://images.unsplash.com/photo-1682879654288-3bc35430b79f",
      filename: "listing-21",
    },
    price: 16000,
    location: "Bikaner",
    country: "India",
    geometry: { type: "Point", coordinates: [73.3119, 28.0229] },
    category: "desert",
  },
  {
    title: "Heritage Haveli",
    desc: "Traditional haveli with authentic Rajasthani décor.",
    image: {
      url: "https://plus.unsplash.com/premium_photo-1678916185493-781b5b61b93b",
      filename: "listing-22",
    },
    price: 9000,
    location: "Mandawa",
    country: "India",
    geometry: { type: "Point", coordinates: [75.1473, 28.0555] },
    category: "castles",
  },
  {
    title: "Seaside Guest House",
    desc: "Budget-friendly guest house near the beach.",
    image: {
      url: "https://plus.unsplash.com/premium_photo-1724701624517-22953482ce56",
      filename: "listing-23",
    },
    price: 3500,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8083, 11.9416] },
    category: "rooms",
  },
  {
    title: "Luxury Spa Resort",
    desc: "Wellness-focused resort with spa therapies.",
    image: {
      url: "https://images.unsplash.com/photo-1599875083042-33b9ee13eec2",
      filename: "listing-24",
    },
    price: 17000,
    location: "Kerala",
    country: "India",
    geometry: { type: "Point", coordinates: [76.2711, 10.8505] },
    category: "trending",
  },
  {
    title: "Modern Studio Apartment",
    desc: "Compact studio ideal for solo travelers.",
    image: {
      url: "https://images.unsplash.com/photo-1648775933902-f633de370964",
      filename: "listing-25",
    },
    price: 5000,
    location: "Hyderabad",
    country: "India",
    geometry: { type: "Point", coordinates: [78.4867, 17.385] },
    category: "rooms",
  },
  {
    title: "Cliffside Cottage",
    desc: "Cottage perched on a cliff with panoramic views.",
    image: {
      url: "https://images.unsplash.com/photo-1689729738817-fb1f4256769d",
      filename: "listing-26",
    },
    price: 9500,
    location: "Lonavala",
    country: "India",
    geometry: { type: "Point", coordinates: [73.4062, 18.7546] },
    category: "mountains",
  },
  {
    title: "Luxury Golf Resort",
    desc: "Resort located beside a scenic golf course.",
    image: {
      url: "https://images.unsplash.com/photo-1733776721893-b7ba2f4e8763",
      filename: "listing-27",
    },
    price: 15500,
    location: "Gurgaon",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0266, 28.4595] },
    category: "trending",
  },
  {
    title: "Cultural Village Stay",
    desc: "Authentic village lifestyle experience.",
    image: {
      url: "https://images.unsplash.com/photo-1671080749770-791e382d681c",
      filename: "listing-28",
    },
    price: 4000,
    location: "Kutch",
    country: "India",
    geometry: { type: "Point", coordinates: [69.8597, 23.7337] },
    category: "farms",
  },
  {
    title: "Skyline View Hotel",
    desc: "Hotel offering breathtaking city skyline views.",
    image: {
      url: "https://images.unsplash.com/photo-1688933758128-83d40ab10b4e",
      filename: "listing-29",
    },
    price: 13000,
    location: "Pune",
    country: "India",
    geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
    category: "iconic",
  },
  {
    title: "Luxury Waterfront Villa",
    desc: "Elegant villa with private waterfront access.",
    image: {
      url: "https://images.unsplash.com/photo-1763467941615-98eaad52f153",
      filename: "listing-30",
    },
    price: 22000,
    location: "Kumarakom",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4263, 9.6175] },
    category: "trending",
  },
];

module.exports = { data: sampleListings };
